### PR TITLE
Added SAS compatibility and other improvements

### PR DESCRIPTION
**Pull request by marrobHD**
Added SAS compatibility and other improvements

### CODE REVIEW

**Comment by Spearfoot** [comment]
Thanks for the contribution! I have a question and two requests.

The question: are you certain that grepping for OK in the result from `smartctl -H /dev/dax` conclusively identifies a SAS drive? I don't own any SAS drives, so I can't test this for myself. 

And the requests:

1> The majority of your changes show up as indentation differences. This makes it hard to see your actual changes. Are you using tabs instead of spaces? I try to use 2 spaces (not tabs) for each level of indentation; this keeps code from stretching out as far on the right of the screen. Would you mind using the original source indentation scheme in your PR?

2> I also prefer to use:

if [ "$sasok" == "OK" ]; then

...instead of...

if [ "$sasok" == "OK ]
       then

...because this reduces the number of indentations as well. Would you mind making these small changes too?

Thanks again!

**Comment by marrobHD** [comment]
da2 is a SAS and da6 is a SATA:
root@xFreeNAS[~]# smartctl -H /dev/da2
smartctl 7.0 2018-12-30 r4883 [FreeBSD 11.3-RELEASE-p9 amd64] (local build)
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK

root@xFreeNAS[~]# smartctl -H /dev/da6                             smartctl 7.0 2018-12-30 r4883 [FreeBSD 11.3-RELEASE-p9 amd64] (local build)
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

root@xFreeNAS[~]# smartctl -H /dev/da6                             smartctl 7.0 2018-12-30 r4883 [FreeBSD 11.3-RELEASE-p9 amd64] (local build)
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

I clean up my changes tomorrow.

**Comment by Spearfoot** [comment]
Yes, I knew that the SAS devices returned their health status differently than SATA devices, as you point out. But what if the SAS drive SMART Health Status is _not_ okay? Looking for 'OK' from the health query would fail in that case, wouldn't it?

I suppose a better way would be to grep the SMART output for each drive, testing for "Transport Protocol: SAS" to identify SAS drives and "SATA Version is" to identify SATA drives. Or something along those lines. That's more trouble, I know...

Thanks for working on this; I've been intending to address SAS drives for quite a while but always seem too busy to get to it.

**Comment by marrobHD** [comment]
You're right. The other way would be to test for "SMART Health Status". You can't do a real smart test on sas drives. That would be stable. But I would prefer your way to test after the protocol. I work tomorrow on that and will show you my changes. I have a lot of time this weekend. Are they any other ideas for implementing other features?

**Comment by Spearfoot** [comment]
You seem to be on the right track when it comes to reporting the SAS info.

Brainstorming a little... Perhaps write two functions to form separate lists of SATA and SAS drives? Something like 'get_SATA_drives()' and 'get_SAS_drives()'? Then iterate over the two lists with the appropriate code, since the two are so different. Might be a cleaner approach.

**Comment by marrobHD** [comment]
I've adopted your desired changes. Mail: https://pastebin.com/hMXBHY3z

**Comment by marrobHD** [comment]
Thanks!

**Comment by Spearfoot** [comment]
marrobHD -- I've worked on the script quite a bit today and committed my changes just now. If you get a chance, would you test it on your system and send me the results? I'd like to see the SAS output... Would be great if you could send me the `smart_report.tmp` file, in particular.

Thanks!

**Comment by marrobHD** [comment]
Nice. https://pastebin.com/0iTUZsRy

But I like this more:
########## SMART status report for /dev/da5 drive (Seagate IronWolf : ZAD3K3PF) ##########

########## SMART status report for /dev/da1 drive (HUS72303CLAR3000 : YXGHL9SK) ##########

**Comment by Spearfoot** [comment]
Thanks for the output file!

Hmmm... Now I see why you widened the 'Command Timeout' field. I'll fold that change back in.

I changed the serial number & brand formatting just to try and keep the output from being so wide. :-)

**Comment by Spearfoot** [comment]
I've committed a version that keeps your wider formatting for the command timeout, and hopefully trims off the trailing spaces on drive identifiers.

**Comment by marrobHD** [comment]
Thanks!

**Comment by Spearfoot** [comment]
You're very welcome!

So you design PCBs? I'm impressed by that kind of skill. I'm an electrical engineer by education, but never worked in the field -- always been a software developer.

And you're from Germany... I love Germany: lived there ~5 years back in the 60's, and have visited a few times since then. Lived in Frankfurt am Main; traveled to Berlin, Heidelberg, Mainz, Wiesbaden, Munchen, Stuttgart, Oberammergau, Berchtesgaden, Landstuhl (Ramstein), and so on.

Anyway, thanks for you help in added SAS support to this script.

**Comment by marrobHD** [comment]
Yes I do and I have so many projects on my table. Respect. I am active in many things. Unfortunately, this has the consequence that I can do most of it only minimally.I'm still looking for what suits me. I've played around with servers and virtualization software a lot in the past few months. Now I have pushed several servers in my closet. It's getting more xD

**Comment by marrobHD** [comment]
What are you doing?

**Comment by Spearfoot** [comment]
You mean what do I do for a career? I'm a software engineer working on flight simulators for the US Air Force.

**Pull request merged**
